<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Estragonia.EditorPlugin.props" />

	<PropertyGroup>
		<AssemblyName>HelloWorld.Editor.Log</AssemblyName>
		<RootNamespace>HelloWorld.Editor.Log</RootNamespace>
	</PropertyGroup>

	<Import Project="..\Estragonia.EditorPlugin.targets" />

</Project>
