<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Godonia.EditorPlugin.props" />

	<PropertyGroup>
		<AssemblyName>HelloWorld.Editor.WorldManager</AssemblyName>
		<RootNamespace>HelloWorld.Editor.WorldManager</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<Import Project="..\Godonia.EditorPlugin.targets" />

</Project>