<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>HelloWorld.Editor.Preview</AssemblyName>
		<RootNamespace>HelloWorld.Editor.Preview</RootNamespace>
		<IsPackable>false</IsPackable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<GodoniaInjectHostScripts>false</GodoniaInjectHostScripts>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\HelloWorld.Editor.SkillTree\HelloWorld.Editor.SkillTree.csproj" />
		<ProjectReference Include="..\HelloWorld.Editor.QuestManager\HelloWorld.Editor.QuestManager.csproj" />
		<ProjectReference Include="..\HelloWorld.Editor.WorldManager\HelloWorld.Editor.WorldManager.csproj" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
	</ItemGroup>

</Project>